cp ../openmrs/api/src/test/java/org/openmrs/api/db/HibernateSearchFullIndexingTest.java api/src/test/java/org/openmrs/api/db/
cp -r ../openmrs/api/src/main/java/org/openmrs/api/search api/src/main/java/org/openmrs/api/
cp ../openmrs/api/src/main/java/org/openmrs/api/SearchService.java api/src/main/java/org/openmrs/api/
cp ../openmrs/api/src/main/java/org/openmrs/api/db/SearchDAO.java api/src/main/java/org/openmrs/api/db/
cp ../openmrs/api/src/main/java/org/openmrs/api/db/hibernate/HibernateSearchDAO.java api/src/main/java/org/openmrs/api/db/hibernate/
cp ../openmrs/api/src/main/java/org/openmrs/api/impl/SearchServiceImpl.java api/src/main/java/org/openmrs/api/impl/
